CREATE DATABASE IF NOT EXISTS nodejs_crud;
USE nodejs_crud;

DROP TABLE IF EXISTS user;

CREATE TABLE user(
    id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome varchar(255) DEFAULT NULL,
    email varchar(255) DEFAULT NULL,
) AUTO_INCREMENT = 1;

